apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaky-update-dep
spec:
  replicas: 4
  selector:
    matchLabels:
      app: flaky-update
  template:
    metadata:
      labels:
        app: flaky-update
    spec:
      containers:
        - name: flaky-update
          image: mluukkai/dwk-app8:v4
          readinessProbe:
            initialDelaySeconds: 10 # Initial delay until the readiness is tested
            periodSeconds: 5 # How often to test
            httpGet:
               path: /healthz
               port: 3541

---

apiVersion: v1
kind: Service
metadata:
  name: flaky-update-svc
spec:
  selector:
    app: flaky-update
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3541
  type: LoadBalancer