apiVersion: v1
kind: ConfigMap
metadata:
  name: log-output-config
  namespace: exercises
data:
  information.txt: this text is from file
  MESSAGE: hello world
  PINGPONG_URL: http://pingpong-service:80/pingpong
  LOG_OUTPUT_PORT: "80"