apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-deployment
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
      - name: log-output
        image: mahansa/log-output:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: MESSAGE
          valueFrom:
            configMapKeyRef:
              name: log-output-config
              key: MESSAGE
        - name: PINGPONG_URL
          valueFrom:
            configMapKeyRef:
              name: log-output-config
              key: PINGPONG_URL
        - name: LOG_OUTPUT_PORT
          valueFrom:
            configMapKeyRef:
              name: log-output-config
              key: LOG_OUTPUT_PORT
        volumeMounts:
        - name: config-volume
          mountPath: "/app/config"
      volumes:
      - name: config-volume
        configMap:
          name: log-output-config
          items:
          - key: information.txt
            path: information.txt
---
apiVersion: v1
kind: Service
metadata:
  name: log-output-service
  namespace: exercises
spec:
  selector:
    app: log-output
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: log-output-ingress
  namespace: exercises
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: log-output-service
            port:
              number: 80