apiVersion: v1
kind: ConfigMap
metadata:
  name: pingpong-config
  namespace: exercises
data:
  PORT: "80"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "password"
  POSTGRES_DB: "pingpongdb"