apiVersion: batch/v1
kind: CronJob
metadata:
  name: wikipedia-todo-generator
  namespace: default
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: todo-generator
            image: curlimages/curl:latest
            args:
            - /bin/sh
            - -c
            - |
              URL=$(curl -s -I https://en.wikipedia.org/wiki/Special:Random | grep -i location | awk '{print $2}' | tr -d '\r')
              echo "Todo: Read $URL"
          restartPolicy: OnFailure