apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
      - name: log-output
        image: mahansa/log-output:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: log-output-service
  namespace: default
spec:
  selector:
    app: log-output
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000