apiVersion: v1
kind: Secret
metadata:
  name: pixabay-apikey
data:
  API_KEY: NTE2MjY0MjUtNDAxYTFlOTIyNTVjODY3ZWM0ZGQwZTYxNQ==
  # base64 encoded value should look something like this, note that this won't work
  # create your own apikey if you would like to test the app
